import { AnalysisResult, IssueSeverity, WalkthroughBlock } from '../types';

// ── Security Score ──────────────────────────────────────────────────────────

export interface SecurityScore {
  score: number;
  label: string;
  color: string;  // tailwind color class
}

export function computeSecurityScore(analysis: AnalysisResult): SecurityScore {
  let errors = 0, warnings = 0, infos = 0;

  for (const issue of analysis.overallIssues || []) {
    if (issue.severity === IssueSeverity.ERROR) errors++;
    else if (issue.severity === IssueSeverity.WARNING) warnings++;
    else infos++;
  }
  for (const comp of analysis.components || []) {
    for (const issue of comp.issues || []) {
      if (issue.severity === IssueSeverity.ERROR) errors++;
      else if (issue.severity === IssueSeverity.WARNING) warnings++;
      else infos++;
    }
  }

  const score = Math.max(0, 100 - errors * 10 - warnings * 3 - infos * 1);

  if (score >= 90) return { score, label: 'Excellent', color: 'text-green-600' };
  if (score >= 70) return { score, label: 'Good', color: 'text-green-500' };
  if (score >= 50) return { score, label: 'Moderate', color: 'text-yellow-500' };
  if (score >= 30) return { score, label: 'Concerning', color: 'text-orange-500' };
  return { score, label: 'Critical', color: 'text-red-600' };
}

// Per-component health for the scorecard slide
export interface ComponentHealth {
  name: string;
  type: string;
  errors: number;
  warnings: number;
  infos: number;
  status: 'clean' | 'warning' | 'error';
}

export function computeComponentHealth(analysis: AnalysisResult): ComponentHealth[] {
  return (analysis.components || []).map(comp => {
    let errors = 0, warnings = 0, infos = 0;
    for (const issue of comp.issues || []) {
      if (issue.severity === IssueSeverity.ERROR) errors++;
      else if (issue.severity === IssueSeverity.WARNING) warnings++;
      else infos++;
    }
    return {
      name: comp.name,
      type: comp.type,
      errors,
      warnings,
      infos,
      status: errors > 0 ? 'error' as const : warnings > 0 ? 'warning' as const : 'clean' as const,
    };
  });
}

// ── Slide Markdown Builder ──────────────────────────────────────────────────

export function buildSlideMarkdown(
  briefing: string,
  mermaidCode: string,
  analysis: AnalysisResult,
  filename: string,
  sourceCode?: string,
  walkthroughBlocks?: WalkthroughBlock[],
): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const score = computeSecurityScore(analysis);
  const health = computeComponentHealth(analysis);

  let errors = 0, warnings = 0, infos = 0;
  for (const issue of analysis.overallIssues || []) {
    if (issue.severity === IssueSeverity.ERROR) errors++;
    else if (issue.severity === IssueSeverity.WARNING) warnings++;
    else infos++;
  }
  for (const comp of analysis.components || []) {
    for (const issue of comp.issues || []) {
      if (issue.severity === IssueSeverity.ERROR) errors++;
      else if (issue.severity === IssueSeverity.WARNING) warnings++;
      else infos++;
    }
  }

  // Title slide
  let md = `# Executive Briefing\n## ${filename}\n\n${date} · ${analysis.language} · ${analysis.components.length} components · Generated by Archlyze`;

  // Briefing content — split into individual slides by ## headings
  const sections = splitByHeadings(briefing);
  for (const section of sections) {
    md += `\n\n---\n\n${section}`;
  }

  // Architecture diagram slide
  if (mermaidCode.trim()) {
    md += `\n\n---\n\n## Architecture Diagram\n\n\`\`\`mermaid\n${mermaidCode}\n\`\`\``;
  }

  // Code walkthrough slides — side-by-side layout (full code, no truncation)
  if (walkthroughBlocks && walkthroughBlocks.length > 0 && sourceCode) {
    const codeLines = sourceCode.split('\n');
    const total = walkthroughBlocks.length;
    const langTag = (analysis.language || '').toLowerCase().replace(/[^a-z]/g, '') || 'text';

    for (let i = 0; i < total; i++) {
      const block = walkthroughBlocks[i];
      const start = Math.max(1, block.startLine);
      const end = Math.min(codeLines.length, block.endLine);
      const snippet = codeLines.slice(start - 1, end).join('\n');

      // Use a custom directive the renderer will parse into a two-column layout
      md += `\n\n---\n\n`;
      md += `:::walkthrough ${i + 1}/${total}: ${block.title}\n`;
      md += `:::lines ${start}–${end}\n`;
      md += `:::code ${langTag}\n${snippet}\n:::endcode\n`;
      md += `:::explain\n${block.explanation}`;
      if (block.risk) {
        md += `\n\n⚠️ **Risk:** ${block.risk}`;
      }
      md += `\n:::endexplain`;
    }
  }

  // Security scorecard slide
  md += `\n\n---\n\n## Security Scorecard\n\n`;
  md += `**Overall Score: ${score.score}/100 — ${score.label}**\n\n`;
  md += `| Metric | Count |\n|--------|-------|\n`;
  md += `| 🔴 Errors | ${errors} |\n`;
  md += `| ⚠️ Warnings | ${warnings} |\n`;
  md += `| ℹ️ Info | ${infos} |\n\n`;

  if (health.length > 0) {
    md += `| Component | Type | Status |\n|-----------|------|--------|\n`;
    for (const h of health) {
      const icon = h.status === 'error' ? '🔴' : h.status === 'warning' ? '⚠️' : '✅';
      md += `| ${h.name} | ${h.type} | ${icon} ${h.errors}E / ${h.warnings}W / ${h.infos}I |\n`;
    }
  }

  return md;
}

function splitByHeadings(md: string): string[] {
  const lines = md.split('\n');
  const sections: string[] = [];
  let current: string[] = [];

  for (const line of lines) {
    if (/^## /.test(line) && current.length > 0) {
      const text = current.join('\n').trim();
      if (text) sections.push(text);
      current = [line];
    } else {
      current.push(line);
    }
  }

  const text = current.join('\n').trim();
  if (text) sections.push(text);

  return sections;
}

// ── Slide Parsing ───────────────────────────────────────────────────────────

export function parseSlides(markdown: string): string[] {
  return markdown
    .split(/\n---\n/)
    .map(s => s.trim())
    .filter(s => s.length > 0);
}

// ── Markdown → HTML Renderer (handles our known template patterns) ──────────

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function inlineMarkdown(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, '<strong class="font-semibold text-gray-900">$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code class="bg-gray-100 text-rust px-1.5 py-0.5 rounded text-sm font-mono">$1</code>');
}

export function renderSlideHtml(slideMarkdown: string): string {
  // Walkthrough slides use a custom directive — render as two-column layout
  if (slideMarkdown.startsWith(':::walkthrough ')) {
    return renderWalkthroughHtml(slideMarkdown);
  }

  const lines = slideMarkdown.split('\n');
  let html = '';
  let inCodeBlock = false;
  let codeBlockLang = '';
  let codeContent = '';
  let inList = false;
  let inTable = false;
  let tableHeaderDone = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Code block toggle — match ``` at start of line (allow trailing whitespace)
    if (/^```/.test(line.trim())) {
      if (inCodeBlock) {
        if (codeBlockLang.toLowerCase() === 'mermaid') {
          html += `<div class="mermaid-block my-6 flex justify-center" data-mermaid="${escapeHtml(codeContent.trim())}"><div class="text-gray-400 text-sm italic p-8 bg-gray-50 rounded-lg border border-gray-200 w-full text-center">Loading diagram…</div></div>`;
        } else {
          html += `<pre class="bg-gray-800 text-gray-100 rounded-lg p-4 text-[13px] font-mono overflow-x-auto my-5 leading-relaxed"><code>${escapeHtml(codeContent)}</code></pre>`;
        }
        inCodeBlock = false;
        codeContent = '';
        codeBlockLang = '';
      } else {
        inCodeBlock = true;
        codeBlockLang = line.trim().slice(3).trim();
      }
      continue;
    }
    if (inCodeBlock) {
      codeContent += line + '\n';
      continue;
    }

    // Close open list
    if (inList && !line.startsWith('- ')) {
      html += '</ul>';
      inList = false;
    }

    // Close open table
    if (inTable && !line.startsWith('|')) {
      html += '</tbody></table></div>';
      inTable = false;
      tableHeaderDone = false;
    }

    // Headings
    if (line.startsWith('### ')) {
      html += `<h3 class="text-xl font-semibold text-gray-700 mt-8 mb-3">${inlineMarkdown(line.slice(4))}</h3>`;
      continue;
    }
    if (line.startsWith('## ')) {
      html += `<h2 class="text-2xl font-bold text-gray-800 mb-4 mt-2">${inlineMarkdown(line.slice(3))}</h2>`;
      continue;
    }
    if (line.startsWith('# ')) {
      html += `<h1 class="text-4xl font-bold mb-3" style="color:#CE422B">${inlineMarkdown(line.slice(2))}</h1>`;
      continue;
    }

    // Bullet lists
    if (line.startsWith('- ')) {
      if (!inList) {
        html += '<ul class="space-y-2 my-4 ml-1">';
        inList = true;
      }
      html += `<li class="flex gap-2.5 text-gray-600 leading-relaxed"><span class="text-rust mt-1 shrink-0 text-lg">•</span><span>${inlineMarkdown(line.slice(2))}</span></li>`;
      continue;
    }

    // Tables
    if (line.startsWith('|')) {
      const cells = line.split('|').slice(1, -1).map(c => c.trim());

      // Skip separator row (|---|---|)
      if (cells.every(c => /^[-:]+$/.test(c))) {
        tableHeaderDone = true;
        continue;
      }

      if (!inTable) {
        html += '<div class="overflow-x-auto my-4"><table class="w-full text-sm border-collapse">';
        html += '<thead><tr>';
        for (const cell of cells) {
          html += `<th class="text-left px-3 py-2 bg-gray-100 font-semibold text-gray-700 border-b-2 border-gray-200">${inlineMarkdown(cell)}</th>`;
        }
        html += '</tr></thead><tbody>';
        inTable = true;
        continue;
      }

      html += '<tr>';
      for (const cell of cells) {
        html += `<td class="px-3 py-2 border-b border-gray-100 text-gray-600">${inlineMarkdown(cell)}</td>`;
      }
      html += '</tr>';
      continue;
    }

    // Empty line
    if (line.trim() === '') {
      html += '<div class="h-2"></div>';
      continue;
    }

    // Regular paragraph
    html += `<p class="text-gray-600 leading-relaxed mb-3">${inlineMarkdown(line)}</p>`;
  }

  // Close any open blocks
  if (inList) html += '</ul>';
  if (inTable) html += '</tbody></table></div>';

  return html;
}

// ── Walkthrough two-column renderer ─────────────────────────────────────────

function renderWalkthroughHtml(slideMarkdown: string): string {
  const lines = slideMarkdown.split('\n');

  let title = '';
  let lineRange = '';
  let codeContent = '';
  let explanation = '';
  let inCode = false;
  let inExplain = false;

  for (const line of lines) {
    if (line.startsWith(':::walkthrough ')) {
      title = line.slice(':::walkthrough '.length);
      continue;
    }
    if (line.startsWith(':::lines ')) {
      lineRange = line.slice(':::lines '.length);
      continue;
    }
    if (line.startsWith(':::code ')) {
      inCode = true;
      continue;
    }
    if (line === ':::endcode') {
      inCode = false;
      continue;
    }
    if (line === ':::explain') {
      inExplain = true;
      continue;
    }
    if (line === ':::endexplain') {
      inExplain = false;
      continue;
    }
    if (inCode) {
      codeContent += (codeContent ? '\n' : '') + line;
      continue;
    }
    if (inExplain) {
      explanation += (explanation ? '\n' : '') + line;
      continue;
    }
  }

  // Build the explanation HTML with inline markdown support
  const explainHtml = explanation
    .split('\n\n')
    .map(para => {
      const trimmed = para.trim();
      if (!trimmed) return '';
      if (trimmed.startsWith('⚠️')) {
        return `<div class="mt-4 p-3 bg-amber-50 border border-amber-200 rounded-lg text-amber-800 text-sm">${inlineMarkdown(trimmed)}</div>`;
      }
      return `<p class="text-gray-600 leading-relaxed mb-3">${inlineMarkdown(trimmed)}</p>`;
    })
    .join('');

  return `
    <div class="flex flex-col h-full">
      <div class="mb-4 shrink-0">
        <h3 class="text-xl font-semibold text-gray-800">Code Walkthrough ${escapeHtml(title)}</h3>
        <span class="text-sm text-gray-400">Lines ${escapeHtml(lineRange)}</span>
      </div>
      <div class="flex gap-6 flex-1 min-h-0">
        <div class="w-1/2 flex flex-col min-h-0">
          <pre class="bg-gray-800 text-gray-100 rounded-lg p-4 text-[12px] font-mono overflow-auto flex-1 leading-relaxed"><code>${escapeHtml(codeContent)}</code></pre>
        </div>
        <div class="w-1/2 overflow-y-auto py-1">
          ${explainHtml}
        </div>
      </div>
    </div>`;
}

// ── Export: Markdown Download ───────────────────────────────────────────────

export function downloadBriefingMarkdown(markdown: string, filename: string) {
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.replace(/\.[^.]+$/, '') + '-briefing.md';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── Export: PPTX via pptxgenjs ──────────────────────────────────────────────

interface ParsedSlide {
  title: string;
  bullets: string[];
  isTitle: boolean;
  tableRows?: string[][];
}

function parseWalkthroughForPptx(slideMarkdown: string): ParsedSlide {
  const lines = slideMarkdown.split('\n');
  let title = '';
  let lineRange = '';
  const bullets: string[] = [];
  let inExplain = false;

  for (const line of lines) {
    if (line.startsWith(':::walkthrough ')) { title = 'Code Walkthrough ' + line.slice(':::walkthrough '.length); continue; }
    if (line.startsWith(':::lines ')) { lineRange = line.slice(':::lines '.length); continue; }
    if (line.startsWith(':::code ') || line === ':::endcode') continue;
    if (line === ':::explain') { inExplain = true; continue; }
    if (line === ':::endexplain') { inExplain = false; continue; }
    if (inExplain) {
      const clean = line.replace(/\*\*/g, '').replace(/\*/g, '').replace(/`/g, '').trim();
      if (clean) bullets.push(clean);
    }
  }

  if (lineRange) bullets.unshift(`Lines ${lineRange}`);
  return { title, bullets, isTitle: false };
}

function parseSlideForPptx(slideMarkdown: string): ParsedSlide {
  // Handle walkthrough directive slides
  if (slideMarkdown.startsWith(':::walkthrough ')) {
    return parseWalkthroughForPptx(slideMarkdown);
  }

  const lines = slideMarkdown.split('\n');
  let title = '';
  const bullets: string[] = [];
  let isTitle = false;
  const tableRows: string[][] = [];
  let inCodeBlock = false;

  for (const line of lines) {
    if (line.startsWith('```')) { inCodeBlock = !inCodeBlock; continue; }
    if (inCodeBlock) continue;

    if (line.startsWith('# ') && !title) {
      title = line.slice(2).replace(/\*\*/g, '');
      isTitle = true;
    } else if (line.startsWith('## ') && !title) {
      title = line.slice(3).replace(/\*\*/g, '');
    } else if (line.startsWith('## ')) {
      // Secondary heading in same slide — treat as subtitle bullet
      bullets.push(line.slice(3).replace(/\*\*/g, ''));
    } else if (line.startsWith('### ')) {
      bullets.push(line.slice(4).replace(/\*\*/g, ''));
    } else if (line.startsWith('- ')) {
      bullets.push(line.slice(2).replace(/\*\*/g, '').replace(/\*/g, ''));
    } else if (line.startsWith('|') && !line.match(/^\|[-:|]+\|$/)) {
      const cells = line.split('|').slice(1, -1).map(c => c.trim());
      tableRows.push(cells);
    } else if (line.trim() && !line.startsWith('|')) {
      const clean = line.replace(/\*\*/g, '').replace(/\*/g, '').replace(/`/g, '').trim();
      if (clean) bullets.push(clean);
    }
  }

  return { title, bullets, isTitle, tableRows: tableRows.length > 0 ? tableRows : undefined };
}

export async function exportToPptx(markdown: string, filename: string): Promise<void> {
  const { default: PptxGenJS } = await import('pptxgenjs');
  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE';

  const slides = parseSlides(markdown);

  for (const slideMd of slides) {
    const parsed = parseSlideForPptx(slideMd);
    const slide = pptx.addSlide();

    slide.addShape('rect' as any, {
      x: 0, y: 0, w: '100%', h: 0.06, fill: { color: 'CE422B' },
    });

    if (parsed.isTitle) {
      slide.addText(parsed.title, {
        x: 0.8, y: 1.5, w: 11.5, fontSize: 32, bold: true, color: 'CE422B',
        fontFace: 'Arial',
      });
      if (parsed.bullets.length > 0) {
        slide.addText(parsed.bullets[0], {
          x: 0.8, y: 2.8, w: 11.5, fontSize: 16, color: '666666',
          fontFace: 'Arial',
        });
      }
      if (parsed.bullets.length > 1) {
        slide.addText(parsed.bullets.slice(1).join('\n'), {
          x: 0.8, y: 3.5, w: 11.5, fontSize: 12, color: '999999',
          fontFace: 'Arial',
        });
      }
    } else {
      slide.addText(parsed.title || '', {
        x: 0.6, y: 0.3, w: 12, fontSize: 22, bold: true, color: '2A2C31',
        fontFace: 'Arial',
      });

      if (parsed.tableRows && parsed.tableRows.length > 0) {
        const tableData = parsed.tableRows.map((row, ri) =>
          row.map(cell => ({
            text: cell,
            options: {
              fontSize: 10,
              fontFace: 'Arial',
              color: ri === 0 ? 'FFFFFF' : '333333',
              bold: ri === 0,
              fill: { color: ri === 0 ? 'CE422B' : ri % 2 === 0 ? 'F5F5F5' : 'FFFFFF' },
            },
          }))
        );
        slide.addTable(tableData, {
          x: 0.6, y: 1.3, w: 12, fontSize: 10,
          border: { type: 'solid', pt: 0.5, color: 'DDDDDD' },
        });

        const afterTable = 1.3 + parsed.tableRows.length * 0.4 + 0.3;
        const remainingBullets = parsed.bullets.filter(
          b => !parsed.tableRows!.some(r => r.some(c => b.includes(c)))
        );
        if (remainingBullets.length > 0) {
          slide.addText(
            remainingBullets.map(b => ({ text: b, options: { bullet: true, fontSize: 13, color: '444444', fontFace: 'Arial', breakType: 'none' as any } })),
            { x: 0.6, y: afterTable, w: 12, h: 5.5 - afterTable, valign: 'top' }
          );
        }
      } else if (parsed.bullets.length > 0) {
        slide.addText(
          parsed.bullets.map(b => ({ text: b, options: { bullet: true, fontSize: 13, color: '444444', fontFace: 'Arial', breakType: 'none' as any } })),
          { x: 0.6, y: 1.3, w: 12, h: 5.5, valign: 'top' }
        );
      }
    }

    slide.addText('Generated by Archlyze', {
      x: 0.6, y: 7.0, w: 12, fontSize: 8, color: 'BBBBBB',
      fontFace: 'Arial',
    });
  }

  await pptx.writeFile({ fileName: filename.replace(/\.[^.]+$/, '') + '-briefing.pptx' });
}
