
import { AnalysisResult, IssueSeverity } from '../types';

export function downloadMarkdownReport(analysis: AnalysisResult, filename: string = 'rustflow-report.md') {
  const date = new Date().toLocaleString();
  
  let md = `# RustFlow Analysis Report
Date: ${date}

## 1. Executive Summary
${analysis.summary}

## 2. Global Issues
`;

  if (analysis.overallIssues.length === 0) {
    md += `_No global issues detected._\n`;
  } else {
    analysis.overallIssues.forEach(issue => {
      md += `- [${issue.severity}] Line ${issue.line}: ${issue.message}\n  > Suggestion: ${issue.suggestion}\n`;
    });
  }

  md += `\n## 3. Component Analysis\n`;

  if (analysis.components.length === 0) {
    md += `_No components detected._\n`;
  } else {
    analysis.components.forEach(comp => {
      md += `### ${comp.type}: \`${comp.name}\`
- **Location**: Lines ${comp.startLine} - ${comp.endLine}
- **Description**: ${comp.description}
`;
      if (comp.dependencies.length > 0) {
        md += `- **Dependencies**: \`${comp.dependencies.join('`, `')}\`\n`;
      }

      if (comp.issues.length > 0) {
        md += `- **Issues**:\n`;
        comp.issues.forEach(issue => {
           const icon = issue.severity === IssueSeverity.ERROR ? '🔴' : issue.severity === IssueSeverity.WARNING ? 'Vk' : 'ℹ️';
           md += `  - ${icon} **${issue.severity}** (Line ${issue.line}): ${issue.message}\n    *Suggestion: ${issue.suggestion}*\n`;
        });
      } else {
        md += `- **Status**: ✅ Clean\n`;
      }
      md += `\n`;
    });
  }

  md += `\n---\n*Generated by RustFlow Analyzer*`;

  // Create blob and download
  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
